### ISSUE TITLE
Add pyprotoc-plugin tests

### ISSUE THREAD

**Issue by benh** [reboot-dev/pyprotoc-plugin#4]

**Comment by CodingCanuck** [comment]
(snipe) adding tests in https://github.com/reboot-dev/pyprotoc-plugin/pull/12

(I'd really like tests before addressing https://github.com/reboot-dev/respect-api/issues/17 )

**Comment by CodingCanuck** [comment]
Fixed by https://github.com/reboot-dev/pyprotoc-plugin/pull/12
